      DOUBLE PRECISION EPSMAC
      PARAMETER (EPSMAC=1.E-6)
      DOUBLE PRECISION DEMEAN,STOPRG,STOPMX,STOPC
      DOUBLE PRECISION ONE,XCOEF1,XCOEF2,XCOEF3,ZERO
      PARAMETER (ONE=1,ZERO=0)
      REAL VNEXT(6)
      SAVE STOPC
